sudo: required

services:
  - docker

# blocklist
branches:
  except:
  - master

# safelist
branches:
  only:
  - v13

jobs:
  include:
    - stage: Build Apache docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -f ./apache/base/Dockerfile -t docker-nextcloud-stage ./apache/base

deploy:
  # deploy v13 to DockerHub
  - provider: script
    script: bash scripts/travisDeploy.sh
    on:
      branch: v13
