sudo: required

services:
  - docker

# blocklist
branches:
  except:
  - master

# safelist
branches:
  only:
  - v13

jobs:
  include:
    - stage: Build Apache docker image - base
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -f ./apache/base/Dockerfile -t docker-nextcloud-$TRAVIS_BRANCH-base ./apache/base
    
    - stage: Build Apache docker image - preview
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -f ./apache/preview/Dockerfile -t docker-nextcloud-$TRAVIS_BRANCH-preview ./apache/preview

deploy:
  # deploy v13 to DockerHub
  - provider: script
    script: bash scripts/travisDeploy.sh
    on:
      branch: v13
