sudo: required

services:
  - docker

# blocklist
branches:
  except:
  - master

# safelist
branches:
  only:
  - v13

env:
  - DOCKER_REPOSITORY=nextcloud

jobs:
  include:
    - stage: Build Apache docker image - base
      script:
      - bash scripts/travisBuildImage.sh $DOCKER_REPOSITORY base
    
    - stage: Build Apache docker image - preview
      script:
      - bash scripts/travisBuildImage.sh $DOCKER_REPOSITORY preview
