sudo: required

services:
  - docker

jobs:
  include:
    - stage: Build Apache docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -f ./apache/Dockerfile -t docker-nextcloud-stage ./apache
      - docker images
      - docker tag docker-nextcloud-stage $DOCKER_USERNAME/travistest:apache $DOCKER_USERNAME/travistest:latest
      - docker push $DOCKER_USERNAME/travistest:apache 
      