sudo: required

services:
  - docker

# blocklist
branches:
  except:
  - master

# safelist
branches:
  only:
  - v14

env:
  - DOCKER_REPOSITORY=nextcloud

jobs:
  include:
    - stage: Build Apache docker image - base
      script:
      - bash scripts/travisBuildImage.sh $DOCKER_REPOSITORY base "stable,production,latest"
    
    - stage: Build Apache docker image - preview
      script:
      - bash scripts/travisBuildImage.sh $DOCKER_REPOSITORY preview

    - stage: Build Apache docker image - imap, smb, full
      name: Build Apache docker image - imap
      script: bash scripts/travisBuildImage.sh $DOCKER_REPOSITORY imap
    - script: bash scripts/travisBuildImage.sh $DOCKER_REPOSITORY smb
      name: Build Apache docker image - smb
    - script: bash scripts/travisBuildImage.sh $DOCKER_REPOSITORY full
      name: Build Apache docker image - full
