#!/bin/bash

#   ===========================================================================
#       This is the post_push hook script for the imap apache build.
#   ===========================================================================

set -e

# Parse image name for repo name
tagStart=$(expr index "$IMAGE_NAME" :)  
repoName=${IMAGE_NAME:0:tagStart-1}

# Get Nextcloud version from my essential Nextcloud Docker image
export $(docker inspect --format='{{range .Config.Env}}{{println .}}{{end}}' migoller/nextcloud:apache | grep NEXTCLOUD_VERSION)
# NEXTCLOUD_VERSION=....

# Split NEXTCLOUD_VERSION for naming the tags
version=( ${NEXTCLOUD_VERSION//./ } )
# TAG naming: version="${version[0]}.${version[1]}.${version[2]}"

# Tag and push image for each additional tag
for tag in {"apache-preview_${NEXTCLOUD_VERSION}","apache-preview_${version[0]}.${version[1]}","apache-preview_${version[0]}"}; do  
    docker tag $IMAGE_NAME ${repoName}:${tag}
    docker push ${repoName}:${tag}
done
